# config.yaml
# 系统配置文件
system:
  name: "AI投资决策系统"
  version: "1.0.0"
  environment: "development"
  
api_keys:
  openai: "${OPENAI_API_KEY}"
  anthropic: "${ANTHROPIC_API_KEY}"
  
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  vector_store_path: "data/vector_store/"
  
models:
  base_url: "http://localhost:11434/api/generate"
  default_model: "qwen3:1.7b"
  temperature: 0.7
  timeout: 3000
  embedding_model: "text-embedding-3-small"
  
agents:
  batch_size: 10
  max_concurrent: 5
  timeout: 30
  
logging:
  level: "INFO"
  file: "logs/system.log"